DROP TABLE IF EXISTS gameData;

CREATE TABLE gameData (
  id INT AUTO_INCREMENT  PRIMARY KEY,
  name VARCHAR(250) NOT NULL,
  secretNumber VARCHAR(250) NOT NULL,
  guess VARCHAR(250) NOT NULL,
  result VARCHAR(250) NOT NULL,
  tries INT NOT NULL
);
